modLoader="javafml"
loaderVersion="[35,)"
issueTrackerURL="https://github.com/LordGrimmauld/createintegration/issues"
logoFile="createintegration_logo.png"
[[mods]]
modId="createintegration"
version="0.1.8"
displayName="Create Integration"
displayURL="https://www.curseforge.com/minecraft/mc-mods/create-integration"
credits="Thanks to Alexander2907 for the Dynamo texture, Thanks to Joe for the Ender Crate texture. Thanks to Dargin for finding my stupid bugs."
authors="Grimmauld"
description='''This mod adds an interface to convert mechanical energy provided from Create machinery to FE.'''
[[dependencies.createintegration]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[35,)" #mandatory
    ordering="NONE"
    side="BOTH"
[[dependencies.createintegration]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.2]" #keep updated
    ordering="NONE"
    side="BOTH"
[[dependencies.createintegration]]
    modId="create"
    mandatory=true
    versionRange="[mc1.16.3_v0.3b,)" #keep updated
    ordering="NONE"
    side="BOTH"
